sudo: false
cache:
  directories:
  - "$HOME/.gradle"
jdk:
- oraclejdk8
before_script: 
script: "./travis-build.sh"
env:
  global:
  - secure: Pjn9Fod57d2LZmHlnn5Ais0O6CGA2S6qiUEImvApGe0gg4HB68HVwfwjjcR0IPnhS4DRSz1bHomz4eFdLSwCnzeVfyHWg4Idilq6oVYz3MV6x3bLVNtiteyeQ6m+VLhUCIZM+TOMYIaVmwLJeY7k1sYECn2nQpzFt/vBUbH6sIGtIfWId4NcHiukN+sQt2Fm9CkwQtdW+RepLk9pPuj+7t6qsQu/DG0hY2MB4gUkUR+q9ifhqsOUlDqQRloOWVJwovei7/UPWgdtNpKg/UqbdmRyfcmOchehgnOBofSGH61C8G44HecBO2N5MFd79CaYbatyuZY2wBoPcodzGtOcdEOlFYPPoZVxFy4CeSgIXRMDSONp+Lga2tsNXH71j/x0Bzjn1jCfcu7rrvZfPfwRv3Dy+BTRKY4gfOcXmOAn3X76QUXY3+1SpvdxoWcs/SCn7zAOUXki1/X+ZfAeEGizDM5Pyn46KfgdW3PkxAi+J6aAY8wcOuht8vMWpW4zWzrPBq/tyP+M6ep5cVULD/iO+HWO1z1ksTDwGYRGPwvZfRwrq1Vt3Rq/DCY2CqdFXzorZkXOXD/Wc97xbjZ02lWM6TqC6FQuPXpDV6bJLiEz47h3R0yofTOF7awoYQbeHndwW0/ma1RIHA3x9JmHEmRC5zy8EkrVd1dsWMen/5EjF4s=
  - secure: eTkQt/nQfac8C3e3AcvyCObCGq0tTldYi3YnAFWpAe+FvLsmyCh9SHfNskyUvl+GsOkDozv22O+Th6okEVbByNm+XDu3+sVD7/lHwup0zrkJMOY7luhQkjgg0oFJTqrlUTDy85/2F8nkSBdxxi+R1TYgHhB61GEe5z7j/DvipoostlLw3Qu83KJNEFwKYuQwJ4dvt7K5Vos0XrVssK8wyFt1CnDSNJVJaFpJ3wAmqBRska0bAxHLKnpPj6ATZbimPRwrm5JspqzKJYrfqb/ktAJ55CdVX6fw8BJ/hkxm0TNHa4ZExnQ1KHKO3Y1htep1tVZEoHzpNT4suum1aK6zjAsq/LVWUJIxTaZypwa1NBhR5vl7oMfM1xH0vqGJZ6vncv46xJdYjU/PMoxH3kJCn6KQ0WSuNJAiGsdPivmcOd2wMUdjt7KPLaU2xaxgv/02etf3CPfOUF3Z1G2YpTWmauwC6ofOUDgRfbKLGdy7itcPD0qu7qgMeLV3xXbpWGU0zFyPG66MOxUM/NBtZBscyuz3nk+z31v+/mi5V3siSJ8IFl/h+m003Mtf+zdl9jBcB/bXnVnoHv9bai9l38EoVUQeMDMFpQR8ZuUixipbHiruKRnlb/V/trEICC/fthjL/zbomJ1GSrOyekOYes1flglRHNBMeI3F8OHgeTfJHPA=
